### ISSUE TITLE
Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'

### ISSUE THREAD

**Issue by yamenarahman** [JeffreyWay/laravel-mix#2383]
-   Laravel Mix Version: 5.0.4 
-   Node Version: 13.13.0
-   NPM Version: 6.14.4
-   OS: macOS 10.15.4

I think this is related to a breaking change in node version 13.13 which conflicts with babel <= 7.9

**Comment by yamenarahman** [comment]
https://github.com/nodejs/node/issues/32852

**Comment by RSickenberg** [comment]
It's due to laravel-mix version using @babel/preset-env@7.8.7.

**Comment by RSickenberg** [comment]
👍

**Comment by oteroweb** [comment]
i add     "@babel/compat-data": "^7.9.0", to package.json, delete package-lock.json and node_module files

**Comment by yunusemredilber** [comment]
I fixed this issue with:
`sudo npm update --depth 5 @babel/preset-env`
after then, same error occurred with "@babel/compat-data/corejs3-shipped-proposals"
and I ran some command for it too:
`sudo npm update --depth 5 @babel/compat-data`
And all my problems are disappeared :)

**Comment by AdrianMrn** [comment]
This was fixed for me by running `yarn upgrade laravel-mix`. The newest version of `laravel-mix` requires a version of `@babel/preset-env` higher than 7.9, which is where this bug is fixed.

**Comment by edumajority** [comment]
> I fixed this issue with:
> `sudo npm update --depth 5 @babel/preset-env`
> After then, same error occurred with "@babel/compat-data/corejs3-shipped-proposals"
> I ran some command for it too:
> `sudo npm update --depth 5 @babel/compat-data`
> Finally, all my problems are disappeared 👍 

That bro, it solved my problems

**Comment by yamenarahman** [comment]
Seems it's fixed.

**Comment by jathanasiou** [comment]
I am still facing this issue in an ember application, after multiple attempts to upgrade all packages or completely rm-ing+DL-ing `node_modules` and `yarn clean cache`.

Error
```
Build Error (broccoli-persistent-filter:Babel > [Babel: ember-cookies]) in ember-cookies/clear-all-cookies.js

Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
Require stack:
- <REDACTED>/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
- <REDACTED>/node_modules/@babel/preset-env/lib/index.js
- <REDACTED>/node_modules/@babel/core/lib/config/files/plugins.js
- <REDACTED>/node_modules/@babel/core/lib/config/files/index.js
- <REDACTED>/node_modules/@babel/core/lib/index.js
- <REDACTED>/node_modules/broccoli-babel-transpiler/lib/worker.js


Stack Trace and Error Report: /tmp/error.dump.1ba436bec65572a52ffe5a2a012c4790.log
```

`package.json`
```json
{
  "private": true,
  "repository": "",
  "author": "",
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "main": "app.js",
  "scripts": {
    "build": "ember build",
    "lint:hbs": "ember-template-lint .",
    "lint:js": "eslint .",
    "start": "ember serve",
    "test": "ember test",
    "publish": "ember build --environment=production",
    "postpublish": "yarn bestzip dist.zip .ebextensions dist/"
  },
  "devDependencies": {
    "@ember/optional-features": "^1.3.0",
    "@fortawesome/ember-fontawesome": "^0.2.1",
    "@fortawesome/free-brands-svg-icons": "^5.13.0",
    "@fortawesome/free-solid-svg-icons": "^5.13.0",
    "bestzip": "^2.1.5",
    "bootstrap": "^4.5.0",
    "broccoli-asset-rev": "^3.0.0",
    "ember-auto-import": "^1.5.3",
    "ember-bootstrap": "^3.1.3",
    "ember-cli-app-version": "^3.2.0",
    "ember-cli-babel": "7.19.0",
    "ember-cli-dependency-checker": "^3.2.0",
    "ember-cli-deploy": "^1.0.2",
    "ember-cli-deploy-build": "^2.0.0",
    "ember-cli-deploy-compress": "^0.3.2",
    "ember-cli-deploy-gzip": "^1.0.1",
    "ember-cli-eslint": "^5.1.0",
    "ember-cli-htmlbars": "^4.3.1",
    "ember-cli-inject-live-reload": "^2.0.2",
    "ember-cli-sass": "^10.0.1",
    "ember-cli-sri": "^2.1.1",
    "ember-cli-template-lint": "^2.0.0",
    "ember-cli-uglify": "^3.0.0",
    "ember-concurrency": "^1.1.7",
    "ember-cookies": "^0.5.2",
    "ember-export-application-global": "^2.0.1",
    "ember-fetch": "^8.0.1",
    "ember-g-recaptcha": "^1.3.0",
    "ember-intl": "^4.3.1",
    "ember-load-initializers": "^2.1.1",
    "ember-local-storage": "^1.7.2",
    "ember-metrics": "^0.14.0",
    "ember-qunit": "^4.6.0",
    "ember-resolver": "^8.0.0",
    "ember-router-scroll": "^3.3.2",
    "ember-search-helper": "^2.0.0",
    "ember-source": "^3.18.1",
    "ember-truth-helpers": "^2.1.0",
    "eslint": "^7.0.0",
    "eslint-plugin-ember": "^8.5.1",
    "loader.js": "^4.7.0",
    "qunit-dom": "^1.2.0",
    "sass": "^1.26.5",
    "sitemap-autogenerator": "^1.2.3"
  },
  "engines": {
    "node": ">= 10.*"
  },
  "dependencies": {
    "@glimmer/component": "^1.0.0",
    "@glimmer/tracking": "^1.0.0",
    "big.js": "^5.2.2",
    "dayjs": "^1.8.26",
    "ember": "^1.0.3",
    "ember-anchor": "^1.0.3",
    "ember-cli": "^3.18.0",
    "ember-useragent": "^0.9.1",
    "query-string": "^6.12.1"
  }
}

**Comment by PLQin** [comment]
我也遇到了这个问题 ， 单单删除 node_modules 没有用， 还得删除 package-lock.json 文件才行

**Comment by Tukale01** [comment]
> I fixed this issue with:
> `sudo npm update --depth 5 @babel/preset-env`
> After then, same error occurred with "@babel/compat-data/corejs3-shipped-proposals"
> I ran some command for it too:
> `sudo npm update --depth 5 @babel/compat-data`
> Finally, all my problems are disappeared :)

This one worked for me. Thanks bro

**Comment by BOTKooper** [comment]
> I fixed this issue with:
> `sudo npm update --depth 5 @babel/preset-env`
> After then, same error occurred with "@babel/compat-data/corejs3-shipped-proposals"
> I ran some command for it too:
> `sudo npm update --depth 5 @babel/compat-data`
> Finally, all my problems are disappeared :)

❤️

**Comment by harshilparmar** [comment]
> 
> 
> I fixed this issue with:
> `sudo npm update --depth 5 @babel/preset-env`
> After then, same error occurred with "@babel/compat-data/corejs3-shipped-proposals"
> I ran some command for it too:
> `sudo npm update --depth 5 @babel/compat-data`
> Finally, all my problems are disappeared :)

Thank you so much...

**Comment by martinlillo-73** [comment]
I have the same issue by trying to install Canvas LMS. The error appears when I run 'yarn install', and I can't find a solution...

**Comment by cribe78** [comment]
> I have the same issue by trying to install Canvas LMS. The error appears when I run 'yarn install', and I can't find a solution...

I've created an issue for that here and noted a workaround: https://github.com/instructure/canvas-lms/issues/1677

**Comment by TravisHi** [comment]
> i add "@babel/compat-data": "^7.9.0", to package.json, delete package-lock.json and node_module files

I had this issue in Gatsby and this solved it for me.

**Comment by rjlfurtado** [comment]
> Corrigi este problema com:
> `sudo npm update --depth 5 @babel/preset-env`
> Depois disso, ocorreu o mesmo erro com "@ babel / compat-data / corejs3-shipped-propostas". Executei
> alguns comandos para ele também:
> `sudo npm update --depth 5 @babel/compat-data`
> Finalmente, todos os meus problemas desapareceram :)

Esse resolveu pra mim!

**Comment by duyngha** [comment]
In my case, I resolved this issue by adding `"@babel/preset-env": "7.9.0"` to `package.json` file. Then, remove `package-lock.json`, re-run `npm install`.

**Comment by Juzepe** [comment]
> This was fixed for me by running `yarn upgrade laravel-mix`. The newest version of `laravel-mix` requires a version of `@babel/preset-env` higher than 7.9, which is where this bug is fixed.

`npm update laravel-mix
` for npm.

**Comment by cutety** [comment]
> > I fixed this issue with:
> > `sudo npm update --depth 5 @babel/preset-env`
> > After then, same error occurred with "@babel/compat-data/corejs3-shipped-proposals"
> > I ran some command for it too:
> > `sudo npm update --depth 5 @babel/compat-data`
> > Finally, all my problems are disappeared 👍
> 
> That bro, it solved my problems

thank you, it works for me.

**Comment by Saabbir** [comment]
> I fixed this issue with:
> `sudo npm update --depth 5 @babel/preset-env`
> After then, same error occurred with "@babel/compat-data/corejs3-shipped-proposals"
> I ran some command for it too:
> `sudo npm update --depth 5 @babel/compat-data`
> Finally, all my problems are disappeared :)

works for me

**Comment by calvin-puram** [comment]
> I fixed this issue with:
> `sudo npm update --depth 5 @babel/preset-env`
> After then, same error occurred with "@babel/compat-data/corejs3-shipped-proposals"
> I ran some command for it too:
> `sudo npm update --depth 5 @babel/compat-data`
> Finally, all my problems are disappeared :)

Thanks this works for me

**Comment by ApolloTang** [comment]
this happen as I upgraded node from 12.4 to 12.9

**Comment by mukama** [comment]
In my case, I was using the wrong version of node for the project. Luckily we use NVM so I run `nvm use` and it worked. You might need to also install your node version. In my case it was `nvm install v12.14.1`

**Comment by abinhho** [comment]
Node: `v14.5.0`

`yarn add @babel/core babel-loader` worked for me.

**Comment by Mhdi-kr** [comment]
> I fixed this issue with:
> `sudo npm update --depth 5 @babel/preset-env`
> After then, same error occurred with "@babel/compat-data/corejs3-shipped-proposals"
> I ran some command for it too:
> `sudo npm update --depth 5 @babel/compat-data`
> Finally, all my problems are disappeared :)
Thank you bro, the day is saved!

**Comment by AndersDJohnson** [comment]
Ran into similar problem, this seemed to solve for me:
```
yarn upgrade --scope @babel
```

**Comment by emmanuelkamala** [comment]
This worked for me:

yarn upgrade --scope @babel

**Comment by developerkarthick** [comment]
> I fixed this issue with: `sudo npm update --depth 5 @babel/preset-env` After then, same error occurred with "@babel/compat-data/corejs3-shipped-proposals" I ran some command for it too: `sudo npm update --depth 5 @babel/compat-data` Finally, all my problems are disappeared :)

solved my problem, Thanks

**Comment by Zeshan3372** [comment]
> * Laravel Mix Version: 5.0.4
> * Node Version: 13.13.0
> * NPM Version: 6.14.4
> * OS: macOS 10.15.4
> 
> I think this is related to a breaking change in node version 13.13 which conflicts with babel <= 7.9


I solved this issue by running a command  **npm audit fix --force**!

**Comment by Zeshan3372** [comment]
Run this Command "**npm audit fix --force**" to solve this issue!

**Comment by paulmcconico** [comment]
Removing node_modules folder and clearing NPM cache worked for me:
`rm -rf node_modules && npm cache clear --force && npm i`

**Comment by yoelvd** [comment]
> I fixed this issue with: `sudo npm update --depth 5 @babel/preset-env` After then, same error occurred with "@babel/compat-data/corejs3-shipped-proposals" I ran some command for it too: `sudo npm update --depth 5 @babel/compat-data` Finally, all my problems are disappeared :)

This fixed my issue in 2022. Wow! kudos bro.
